schema_version = "1.0.0"

id = "alexandria_overhaul"
version = "0.5.51"
name = "AlxOverHaul"
tagline = "Simplify Blender"
maintainer = "Valeria Bosco[ValyArhal] <https://github.com/Valery-AA>"
type = "add-on"

permissions = ["files", "network"]
website = "https://github.com/Valery-AA/AlxOverHaul"

tags = ["User Interface", "Mesh", "Modeling", "Rigging"]

blender_version_min = "4.2.0"
blender_version_max = "4.3.0"

license = [
  "SPDX:GPL-3.0-only",
]

copyright = [
  "2023 Valeria Bosco",
]